version: '3.9'

services:
  djanghi-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${UI_IMAGE_NAME}
    command: yarn ${BUILD_STAGE}
    volumes:
      - '.:/src'
