version: '3.9'

services:

  djanghi-ui:
    container_name: djanghi-ui
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn ${BUILD_STAGE}
    volumes:
      - '.:/src'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true